const productsData = [
  {
    id: 1,
    imageSrc: 'https://m.media-amazon.com/images/I/71WNGfT4rLL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/81hdL5t1FSL._SL1500_.jpg',
    title: 'Premium Wireless Headphones',
    description: 'Experience high-quality sound with our wireless headphones.',
    buttonText: 'Learn more',
    price: '$149.99',
    link: '/product/premium-wireless-headphones',
    category: 'Electronics',
  },
  {
    id: 2,
    imageSrc: 'https://m.media-amazon.com/images/I/71mi0VhSpbL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/710ch6+DskL._SL1500_.jpg',
    title: 'Modern Stainless Steel Watch',
    description: 'Stay stylish and punctual with our modern stainless steel watch.',
    buttonText: 'Learn more',
    price: '$199.99',
    link: '/product/modern-stainless-steel-watch',
    category: 'Fashion',
  },
  {
    id: 3,
    imageSrc: 'https://m.media-amazon.com/images/I/61Ur6uVWDML._SL1200_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/61QKuHZep-L._SL1200_.jpg',
    title: 'Organic Aloe Vera Skincare Set',
    description: 'Revitalize your skin with our organic aloe vera skincare set.',
    buttonText: 'Learn more',
    price: '$39.99',
    link: '/product/organic-aloe-vera-skincare-set',
    category: 'Beauty',
  },
  {
    id: 4,
    imageSrc: 'https://m.media-amazon.com/images/I/61DgG640+0S._SL1200_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/6199WPuV0CS._SL1200_.jpg',
    title: "Professional Chef's Knife Set",
    description: "Enhance your culinary skills with our premium chef's knife set.",
    buttonText: 'Learn more',
    price: '$129.99',
    link: '/product/professional-chefs-knife-set',
    category: 'Kitchen',
  },
  {
    id: 5,
    imageSrc: 'https://m.media-amazon.com/images/I/814WyUlzbZL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/71UDH7bPHLL._SL1500_.jpg',
    title: 'UltraSoft Bedding Collection',
    description: 'Indulge in luxury sleep with our UltraSoft bedding collection.',
    buttonText: 'Learn more',
    price: '$249.99',
    link: '/product/ultrasoft-bedding-collection',
    category: 'Home',
  },
  {
    id: 6,
    imageSrc: 'https://m.media-amazon.com/images/I/61icsCcbdKL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/41NaPrV2fPL.jpg',
    title: 'FitnessTracker Smartwatch',
    description: 'Track your fitness journey with our advanced smartwatch.',
    buttonText: 'Learn more',
    price: '$179.99',
    link: '/product/fitnesstracker-smartwatch',
    category: 'Fitness',
  },
  {
    id: 7,
    imageSrc: 'https://m.media-amazon.com/images/I/71-ZmhEo-aL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/81HC4VgK7bL._SL1500_.jpg',
    title: 'Luxury Leather Office Chair',
    description: 'Upgrade your workspace with our comfortable leather office chair.',
    buttonText: 'Learn more',
    price: '$299.99',
    link: '/product/luxury-leather-office-chair',
    category: 'Office',
  },
  {
    id: 8,
    imageSrc: 'https://m.media-amazon.com/images/I/81IiODmJvnL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/81lx9FeyNuL._SL1500_.jpg',
    title: 'Gourmet Coffee Sampler Set',
    description: 'Savor the finest flavors with our gourmet coffee sampler set.',
    buttonText: 'Learn more',
    price: '$29.99',
    link: '/product/gourmet-coffee-sampler-set',
    category: 'Food & Beverage',
  },
  {
    id: 9,
    imageSrc: 'https://m.media-amazon.com/images/I/81GzRHqG1VL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/817jHCTpZJL._SL1500_.jpg',
    title: 'Portable Bluetooth Speaker',
    description: 'Enjoy music on-the-go with our portable Bluetooth speaker.',
    buttonText: 'Learn more',
    price: '$69.99',
    link: '/product/portable-bluetooth-speaker',
    category: 'Electronics',
  },
  {
    id: 10,
    imageSrc: 'https://m.media-amazon.com/images/I/51+occNIX3L._UL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/81HoHv+UlOL._UL1500_.jpg',
    title: 'Classic Polarized Sunglasses',
    description: 'Stay cool and protected with our classic polarized sunglasses.',
    buttonText: 'Learn more',
    price: '$89.99',
    link: '/product/classic-polarized-sunglasses',
    category: 'Fashion',
  },
  {
    id: 11,
    imageSrc: 'https://m.media-amazon.com/images/I/51F8rlBZ6ZL._SL1000_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/61btKit-RML._SL1500_.jpg',
    title: 'Natural Bamboo Cutting Board',
    description: 'Chop and prep with our eco-friendly natural bamboo cutting board.',
    buttonText: 'Learn more',
    price: '$24.99',
    link: '/product/natural-bamboo-cutting-board',
    category: 'Kitchen',
  },
  {
    id: 12,
    imageSrc: 'https://m.media-amazon.com/images/I/71KyJZBSDqL._SL1200_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/61P3HAmqXML._SL1200_.jpg',
    title: 'Hydrating Facial Mask Set',
    description: "Revive your skin's radiance with our hydrating facial mask set.",
    buttonText: 'Learn more',
    price: '$19.99',
    link: '/product/hydrating-facial-mask-set',
    category: 'Beauty',
  },
  {
    id: 13,
    imageSrc: 'https://m.media-amazon.com/images/I/81S8jikRzGL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/81tEJ0HH+xL._SL1500_.jpg',
    title: 'Professional DSLR Camera',
    description: "Capture life's moments in stunning detail with our DSLR camera.",
    buttonText: 'Learn more',
    price: '$899.99',
    link: '/product/professional-dslr-camera',
    category: 'Electronics',
  },
  {
    id: 14,
    imageSrc: 'https://m.media-amazon.com/images/I/71ktypoXZGL._SL1000_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/71KNmefzewL._SL1000_.jpg',
    title: 'Luxury Velvet Throw Blanket',
    description: 'Stay cozy and stylish with our luxury velvet throw blanket.',
    buttonText: 'Learn more',
    price: '$79.99',
    link: '/product/luxury-velvet-throw-blanket',
    category: 'Home',
  },
  {
    id: 15,
    imageSrc: 'https://m.media-amazon.com/images/I/51w7XECplJL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/61YmkdvN9NL._SL1500_.jpg',
    title: 'Smart Home Security System',
    description: 'Protect your home with our advanced smart home security system.',
    buttonText: 'Learn more',
    price: '$299.99',
    link: '/product/smart-home-security-system',
    category: 'Home',
  },
  {
    id: 16,
    imageSrc: 'https://m.media-amazon.com/images/I/514sV9DgfyL._SL1200_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/61tKj53g8YL._SL1500_.jpg',
    title: 'Yoga & Meditation Mat',
    description: 'Find balance and tranquility with our yoga and meditation mat.',
    buttonText: 'Learn more',
    price: '$49.99',
    link: '/product/yoga-meditation-mat',
    category: 'Fitness',
  },
  {
    id: 17,
    imageSrc: 'https://m.media-amazon.com/images/I/71GVXGwGDwL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/71SU-hmlq1L._SL1500_.jpg',
    title: 'Elegant Crystal Chandelier',
    description: 'Illuminate your space with our elegant crystal chandelier.',
    buttonText: 'Learn more',
    price: '$399.99',
    link: '/product/elegant-crystal-chandelier',
    category: 'Home',
  },
  {
    id: 18,
    imageSrc: 'https://m.media-amazon.com/images/I/71bauCnIGdL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/71RSfwymvlL._SL1500_.jpg',
    title: 'All-Natural Protein Powder',
    description: 'Fuel your workouts with our all-natural protein powder.',
    buttonText: 'Learn more',
    price: '$34.99',
    link: '/product/all-natural-protein-powder',
    category: 'Fitness',
  },
  {
    id: 19,
    imageSrc: 'https://m.media-amazon.com/images/I/81MyCcb60EL._UL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/71VClhs660L._UL1500_.jpg',
    title: 'Stylish Leather Crossbody Bag',
    description: 'Accessorize with our stylish leather crossbody bag.',
    buttonText: 'Learn more',
    price: '$129.99',
    link: '/product/stylish-leather-crossbody-bag',
    category: 'Fashion',
  },
  {
    id: 20,
    imageSrc: 'https://m.media-amazon.com/images/I/71vmdX0F7iL._SL1500_.jpg',
    hoverImageSrc: 'https://m.media-amazon.com/images/I/71qytpASZlL._SL1500_.jpg',
    title: 'Outdoor Adventure Backpack',
    description: 'Embark on adventures with our rugged outdoor adventure backpack.',
    buttonText: 'Learn more',
    price: '$79.99',
    link: '/product/outdoor-adventure-backpack',
    category: 'Travel',
  },
];

export default productsData;
